version: '3.8'
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # depends_on:
    #   - db

#   db:
#     image: mysql:5.7
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: laraveluser
#       MYSQL_PASSWORD: laravelpassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - dbdata:/var/lib/mysql

# volumes:
#   dbdata:

# DBを使用する場合はコメントアウトを外す
